# Generated by Django 2.2.3 on 2019-07-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField()),
                ('station_name', models.CharField(max_length=50)),
            ],
        ),
    ]
